[files]
extend-exclude = [
    "/2020/05/pr_to_sqlx_document.md",
    "/2021/07/beginning_linux_programming_2.md"
]

[default.extend-words]
ser = "ser" # serde
cros = "cros"
iterm = "iterm"
sie = "sie"
